services:
  - type: web
    name: rincon-psicope-v2
    env: static
    buildCommand: npm install && chmod -R +x node_modules/.bin && npx vite build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html